# fly.toml file generated for love-letters on 2023-04-17T14:19:09+01:00

app = "love-letters"
primary_region = "lhr"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
